spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.188.188:3306/orangeblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .html
server:
  port: 9000
logging:
  level:
    root: info
    com.wt: debug
logback:
  logdir: F:/logs
  appname: orangeblog
# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

